
all:
	@cp Dotbash_profile ~/.bash_profile
	@cp Dotbashrc ~/.bashrc
	@ln -s /Users/ryan/Library/ /Users/ryan/Desktop/Library
	@echo "Bash files installed..."
	@echo
	@echo "Hints:"
	@echo "  Now install Brew and Anaconda."
	@echo "  You can install brew, then wget via brew,
	@echo "  then Anaconda via wget and bash."
	@echo "  Brew can also install nodejs and docker."
